from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    ProfileUpdateView,
    ProfileView,
    IdeaCreateView,
    IdeaListView,
    CategoryListView,
    IdeaUpdateView,
    IdeaDeleteView,
    ReportCreateView,
    LikeIdeaView,
    ChangePasswordView,
    DeleteAccountView,
    SearchView,
    CommentListCreateView,
    CommentListCreateView,
    CommentDeleteView,
    CollaborationRequestView,
    CollaborationApproveRejectView, 
    NotificationListView,
    NotificationMarkReadView,
    MessageListCreateView,
    CollaborationListView,
    GroupMembersView, RemoveMemberView, LeaveGroupView
)
from rest_framework_simplejwt.views import TokenRefreshView


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('ideas/', IdeaCreateView.as_view(), name='idea_create'),
    path('ideas/list/', IdeaListView.as_view(), name='idea_list'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('ideas/<int:pk>/', IdeaUpdateView.as_view(), name='idea_update'),
    path('ideas/<int:pk>/delete/', IdeaDeleteView.as_view(), name='idea_delete'),
    path('reports/', ReportCreateView.as_view(), name='report_create'),
    path('ideas/like/<int:idea_id>/', LikeIdeaView.as_view(), name='idea_like'),
    path('auth/change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('auth/delete-account/', DeleteAccountView.as_view(), name='delete_account'),
    path('search/', SearchView.as_view(), name='search'),
    path('ideas/<int:idea_id>/comments/', CommentListCreateView.as_view(), name='comment_list_create'),    
    path('ideas/<int:idea_id>/comments/', CommentListCreateView.as_view(), name='comment_list_create'),
    path('comments/<int:comment_id>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('ideas/<int:idea_id>/collab/request/', CollaborationRequestView.as_view(), name='collab_request'),
    path('collab/<int:collab_id>/action/', CollaborationApproveRejectView.as_view(), name='collab_action'),
    path('notifications/', NotificationListView.as_view(), name='notification_list'),
    path('notifications/<int:notification_id>/read/', NotificationMarkReadView.as_view(), name='notification_read'),
    path('ideas/<int:idea_id>/messages/', MessageListCreateView.as_view(), name='message_list_create'),
    path('collaborations/', CollaborationListView.as_view(), name='collaborations_list'),
    path('ideas/<int:idea_id>/group-members/', GroupMembersView.as_view(), name='group_members'),
    path('collaborations/remove/', RemoveMemberView.as_view(), name='remove_member'),
    path('collaborations/leave/', LeaveGroupView.as_view(), name='leave_group'),
]