# Generated by Django 5.2.5 on 2025-09-02 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='idea',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_in_category', to='core.category'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_categories', to='core.idea'),
        ),
    ]
