# Generated by Django 5.2.5 on 2025-09-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ideacategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='categories',
        ),
    ]
