# Generated by Django 5.2.5 on 2025-09-03 14:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_idea_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=list, validators=[core.models.validate_social_links]),
        ),
    ]
