# Generated by Django 5.2.5 on 2025-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
